In [1]:
import pandas as pd
import numpy as np

### Load the data

In [3]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [4]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

In [5]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [6]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours']>data_preprocessed['Absenteeism Time in Hours'].median(),1,0)

In [7]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [8]:
data_preprocessed['Excessive Absenteeism'] = targets
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

### Check if the targets are balanced or not

In [10]:
targets.sum()/targets.shape[0]

0.45571428571428574

In [11]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Day of the Week', 'Daily Work Load Average', 'Distance to Work'], axis=1)

In [12]:
data_with_targets is data_preprocessed

False

In [13]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         1         0         0         0            7   
4         0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                     289   33               30          0         2     1   
1                     118   50               31          0         1     0   
2                     179   38               31          0         0     0   
3                     279   39               24          0         2     0   
4                     289   33               30          0         2     1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [14]:
data_with_targets.iloc[:,0:14]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                       289   33               30          0         2     1   
1                       118   50               31          0         1     0   
2                       179   38               31          0         0     0   
3                       279   39               24          0         2     0   
4                       289   33               30          0         2     1   
..                      ...  ...              ...        ...       ...   ...   
695                     179   40               22          1         2     0   
696                     225   28               24          0         1     2   
697                     330   28               25          1         0     0   
698                     235   32               25          1         0     0   
699                     291   40               25          0         1     1   

     Excessive Absenteeism  
0                        1  
1                        0  
2                        0  
3                        1  
4                        0  
..                     ...  
695                      1  
696                      0  
697                      1  
698                      0  
699                      0  

[700 rows x 12 columns]

In [15]:
data_with_targets.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                       289   33               30          0         2     1  
1                       118   50               31          0         1     0  
2                       179   38               31          0         0     0  
3                       279   39               24          0         2     0  
4                       289   33               30          0         2     1  
..                      ...  ...              ...        ...       ...   ...  
695                     179   40               22          1         2     0  
696                     225   28               24          0         1     2  
697                     330   28               25          1         0     0  
698                     235   32               25          1         0     0  
699                     291   40               25          0         1     1  

[700 rows x 11 columns]

In [16]:
unscaled_inputs = data_with_targets.iloc[:,:-1]
unscaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                       289   33               30          0         2     1  
1                       118   50               31          0         1     0  
2                       179   38               31          0         0     0  
3                       279   39               24          0         2     0  
4                       289   33               30          0         2     1  
..                      ...  ...              ...        ...       ...   ...  
695                     179   40               22          1         2     0  
696                     225   28               24          0         1     2  
697                     330   28               25          1         0     0  
698                     235   32               25          1         0     0  
699                     291   40               25          0         1     1  

[700 rows x 11 columns]

### Standardize the Data

In [18]:
#from sklearn.preprocessing import StandardScaler

In [19]:
#absenteeism_scaler = StandardScaler()

In [20]:
# Import necessary libraries
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np

# Create the CustomScaler class
class CustomScaler(BaseEstimator, TransformerMixin): 
    
    def __init__(self, columns, copy=True, with_mean=True, with_std=True):
        # Initialize the StandardScaler
        self.copy = copy
        self.with_mean = with_mean
        self.with_std = with_std
        self.scaler = StandardScaler(copy=self.copy, with_mean=self.with_mean, with_std=self.with_std)
        # Specify the columns to be scaled
        self.columns = columns
        self.mean_ = None
        self.var_ = None
    
    # The fit method
    def fit(self, X, y=None):
        # Fit the scaler on the specified columns
        self.scaler.fit(X[self.columns], y)
        # Capture mean and variance from the StandardScaler
        self.mean_ = self.scaler.mean_
        self.var_ = self.scaler.var_
        return self
    
    # The transform method
    def transform(self, X, y=None, copy=None):
        # Record the initial column order
        init_col_order = X.columns
        
        # Scale the specified columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        
        # Identify columns that were not scaled
        X_not_scaled = X.loc[:, ~X.columns.isin(self.columns)]
        
        # Concatenate scaled and non-scaled features and retain the original order
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]


In [21]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [22]:
#columns_to_scale = ['Month Value', 'Transportation Expense','Age', 'Body Mass Index', 'Children', 'Pets']

In [23]:
columns_to_omit = ['Reason_1','Reason_2','Reason_3','Reason_4','Education'] #this is a better way to do it.

In [24]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [25]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [26]:
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'])

In [27]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [28]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1     0.182726   
1           0         0         0         0     0.182726   
2           0         0         0         1     0.182726   
3           1         0         0         0     0.182726   
4           0         0         0         1     0.182726   
..        ...       ...       ...       ...          ...   
695         1         0         0         0    -0.388293   
696         1         0         0         0    -0.388293   
697         1         0         0         0    -0.388293   
698         0         0         0         1    -0.388293   
699         0         0         0         1    -0.388293   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
0                  1.005844 -0.536062         0.767431          0  0.880469   
1                 -1.574681  2.130803         1.002633          0 -0.019280   
2                 -0.654143  0.248310         1.002633          0 -0.919030   
3                  0.854936  0.405184        -0.643782          0  0.880469   
4                  1.005844 -0.536062         0.767431          0  0.880469   
..                      ...       ...              ...        ...       ...   
695               -0.654143  0.562059        -1.114186          1  0.880469   
696                0.040034 -1.320435        -0.643782          0 -0.019280   
697                1.624567 -1.320435        -0.408580          1 -0.919030   
698                0.190942 -0.692937        -0.408580          1 -0.919030   
699                1.036026  0.562059        -0.408580          0 -0.019280   

         Pets  
0    0.268487  
1   -0.589690  
2   -0.589690  
3   -0.589690  
4    0.268487  
..        ...  
695 -0.589690  
696  1.126663  
697 -0.589690  
698 -0.589690  
699  0.268487  

[700 rows x 11 columns]

In [29]:
scaled_inputs.shape

(700, 11)

### Splitting into Training and Testing

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size =0.8, random_state = 20)

In [33]:
print(x_train.shape,y_train.shape)

(560, 11) (560,)


In [34]:
print(x_test.shape,y_test.shape)

(140, 11) (140,)


### Logistic Regression With Sklearn

In [36]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

### Train the Model

In [38]:
reg = LogisticRegression()
reg.fit(x_train, y_train)

LogisticRegression()

In [39]:
reg.score(x_train, y_train)

0.7767857142857143

### Manually Check the Accuracy

In [41]:
model_outputs = reg.predict(x_train)

In [42]:
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [43]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [44]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [45]:
np.sum(model_outputs == y_train)

435

In [46]:
Accuracy = np.sum(model_outputs == y_train)/model_outputs.shape[0]

In [47]:
Accuracy

0.7767857142857143

### Find the intercpt and coefficients

In [49]:
reg.intercept_

array([-1.70279795])

In [50]:
reg.coef_

array([[ 2.86345705,  0.67642937,  3.2008837 ,  0.8954063 ,  0.16473358,
         0.61503778, -0.17556074,  0.28391799, -0.24220521,  0.34389912,
        -0.28115612]])

In [51]:
scaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [52]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [53]:
feature_names = unscaled_inputs.columns.values

In [54]:
summary_table = pd.DataFrame(columns=['feature_name'], data = feature_names)
summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table

feature_name  Coefficient
0                 Reason_1     2.863457
1                 Reason_2     0.676429
2                 Reason_3     3.200884
3                 Reason_4     0.895406
4              Month Value     0.164734
5   Transportation Expense     0.615038
6                      Age    -0.175561
7          Body Mass Index     0.283918
8                Education    -0.242205
9                 Children     0.343899
10                    Pets    -0.281156

In [55]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

feature_name  Coefficient
0                Intercept    -1.702798
1                 Reason_1     2.863457
2                 Reason_2     0.676429
3                 Reason_3     3.200884
4                 Reason_4     0.895406
5              Month Value     0.164734
6   Transportation Expense     0.615038
7                      Age    -0.175561
8          Body Mass Index     0.283918
9                Education    -0.242205
10                Children     0.343899
11                    Pets    -0.281156

In [56]:
summary_table['Odds_Ratio'] = np.exp(summary_table.Coefficient)
summary_table

feature_name  Coefficient  Odds_Ratio
0                Intercept    -1.702798    0.182173
1                 Reason_1     2.863457   17.521997
2                 Reason_2     0.676429    1.966842
3                 Reason_3     3.200884   24.554219
4                 Reason_4     0.895406    2.448330
5              Month Value     0.164734    1.179079
6   Transportation Expense     0.615038    1.849726
7                      Age    -0.175561    0.838986
8          Body Mass Index     0.283918    1.328324
9                Education    -0.242205    0.784895
10                Children     0.343899    1.410436
11                    Pets    -0.281156    0.754910

In [57]:
summary_table.sort_values('Odds_Ratio', ascending = False)

feature_name  Coefficient  Odds_Ratio
3                 Reason_3     3.200884   24.554219
1                 Reason_1     2.863457   17.521997
4                 Reason_4     0.895406    2.448330
2                 Reason_2     0.676429    1.966842
6   Transportation Expense     0.615038    1.849726
10                Children     0.343899    1.410436
8          Body Mass Index     0.283918    1.328324
5              Month Value     0.164734    1.179079
7                      Age    -0.175561    0.838986
9                Education    -0.242205    0.784895
11                    Pets    -0.281156    0.754910
0                Intercept    -1.702798    0.182173

### Testing the Model

In [109]:
reg.score(x_test, y_test)

0.75

In [111]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.71108659, 0.28891341],
       [0.58487658, 0.41512342],
       [0.4357923 , 0.5642077 ],
       [0.78192704, 0.21807296],
       [0.08396961, 0.91603039],
       [0.3337842 , 0.6662158 ],
       [0.30040193, 0.69959807],
       [0.12870366, 0.87129634],
       [0.78738431, 0.21261569],
       [0.74815559, 0.25184441],
       [0.4882329 , 0.5117671 ],
       [0.22201608, 0.77798392],
       [0.07004997, 0.92995003],
       [0.73831941, 0.26168059],
       [0.30935375, 0.69064625],
       [0.54881163, 0.45118837],
       [0.54688393, 0.45311607],
       [0.53520545, 0.46479455],
       [0.40814251, 0.59185749],
       [0.05111112, 0.94888888],
       [0.69823338, 0.30176662],
       [0.78192704, 0.21807296],
       [0.41862406, 0.58137594],
       [0.41862406, 0.58137594],
       [0.24280789, 0.75719211],
       [0.74536916, 0.25463084],
       [0.50919909, 0.49080091],
       [0.86031975, 0.13968025],
       [0.19705391, 0.80294609],
       [0.78192704, 0.21807296],
       [0.

In [113]:
predicted_proba.shape

(140, 2)

In [115]:
predicted_proba[:,1]

array([0.28891341, 0.41512342, 0.5642077 , 0.21807296, 0.91603039,
       0.6662158 , 0.69959807, 0.87129634, 0.21261569, 0.25184441,
       0.5117671 , 0.77798392, 0.92995003, 0.26168059, 0.69064625,
       0.45118837, 0.45311607, 0.46479455, 0.59185749, 0.94888888,
       0.30176662, 0.21807296, 0.58137594, 0.58137594, 0.75719211,
       0.25463084, 0.49080091, 0.13968025, 0.80294609, 0.21807296,
       0.37029364, 0.67980738, 0.68679655, 0.53522734, 0.21807296,
       0.53630634, 0.22059591, 0.73886295, 0.40299345, 0.60385261,
       0.2101594 , 0.44369926, 0.23719299, 0.38370245, 0.83057135,
       0.57189487, 0.68926955, 0.28891341, 0.2189278 , 0.20245867,
       0.57229032, 0.31820241, 0.6662158 , 0.27096598, 0.83551456,
       0.43812901, 0.88798838, 0.22822215, 0.32492799, 0.33532841,
       0.69578708, 0.6556765 , 0.29128615, 0.79778567, 0.20459297,
       0.26997817, 0.08313978, 0.22059591, 0.73760391, 0.29961757,
       0.22059591, 0.28162875, 0.90664491, 0.46062112, 0.60531

### Save the Model

In [118]:
import pickle

In [120]:
with open('model', 'wb') as file:
    pickle.dump(reg,file)

In [122]:
with open('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)